/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignment3;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.*;
import java.awt.LayoutManager;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author hamma
 */
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        loaddata();
        this.setLocationRelativeTo(null);
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Library Managment System");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Add Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Edit Book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Delete Book");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setText("Show Popularity");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addGap(79, 79, 79)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        JDialog dialog = new JDialog(this,"Pop-Up Window", true);

                // Add the panel to the JDialog.
                dialog.add(new AddForm(dialog));

                // Set the size and visibility of the JDialog.
                dialog.setSize(500, 300);
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
                this.loaddata();
                
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JDialog dialog = new JDialog(this,"Pop-Up Window", true);

                // Add the panel to the JDialog.
                dialog.add(new EditForm(dialog));

                // Set the size and visibility of the JDialog.
                dialog.setSize(500, 300);
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
                this.loaddata();
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         JDialog dialog = new JDialog(this,"Pop-Up Window", true);

                
                
                
                dialog.add(new DeleteForm(dialog));

                // Set the size and visibility of the JDialog.
                dialog.setSize(500, 300);
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
                this.loaddata();
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       Map<String, Integer> bookPopularity;
         bookPopularity = new HashMap<>();
          try (BufferedReader reader = new BufferedReader(new FileReader("/D:/Java Development/Assignment3/src/main/java/com/mycompany/assignment3/data.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                // Assuming data is in the format: "Book Name: Popularity"
                String[] parts = line.split(",");
                if (parts.length == 4) {
                    String bookName = parts[0].trim();
                    int popularity = Integer.parseInt(parts[3].trim());
                    bookPopularity.put(bookName, popularity);
                }
            }
            
            reader.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
       
        
  
       
    
       
         JFrame chartFrame = new JFrame("Popularity Chart");
        chartFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        chartFrame.setSize(1000, 500);

        // Create a custom JPanel for displaying the chart (you can use libraries like JFreeChart for more advanced charts)
        JPanel chartPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);

                       int barWidth = 30;
                int x = 50;

                for (String bookName : bookPopularity.keySet()) {
                    int popularity = bookPopularity.get(bookName);
                    int barHeight = popularity * 30; // You may need to adjust this scaling

                    g.setColor(Color.DARK_GRAY);
                    g.fillRect(x, 300 - barHeight, barWidth, barHeight);

                    g.setColor(Color.black);
                    g.drawString(bookName, x, 320);

                    x += barWidth + 40; // Adjust the spacing between bars
                }
            }
        };

         chartFrame.add(chartPanel,BorderLayout.CENTER);
          
          
        chartFrame.setVisible(true);
        
             
      
   
    }//GEN-LAST:event_jButton4ActionPerformed
   

   
    public void loaddata(){
    DefaultTableModel model = new DefaultTableModel();
    
        // Add columns to the model
      
        model.addColumn("Title");
        model.addColumn("Author");
        model.addColumn("Year");
        model.addColumn(" ");
        
        jTable1.setModel(model);

        // Read the data from the .txt file  
        try {
            File file = new File("/D:/Java Development/Assignment3/src/main/java/com/mycompany/assignment3/data.txt");
            FileReader reader = new FileReader(file);
            BufferedReader br = new BufferedReader(reader);

            String line;
            
            while ((line = br.readLine()) != null) {
               
                String[] data = line.split(",");
                data[3]=" ";
                // Add the data to the model
                model.addRow(data);
            }

            br.close();
            reader.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
   // Set the table cell renderer for the table column
   
 ReadButtonTableCellRenderer render=  new ReadButtonTableCellRenderer();
jTable1.getColumnModel().getColumn(3).setCellRenderer(render);
jTable1.getColumnModel().getColumn(3).setCellEditor(new ButtonEditor(new JCheckBox()));

jTable1.revalidate();

jTable1.getColumnModel().getColumn(0).setPreferredWidth(220);
jTable1.getColumnModel().getColumn(1).setPreferredWidth(210);
jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);

// Set the auto-resize mode of the table
jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);



     jTable1.addMouseListener(new MouseAdapter(){
        int heli=-1;
            
            @Override
        public void mouseMoved(MouseEvent e){
                
            int row=jTable1.rowAtPoint(e.getPoint());
            if(row!=heli &&row>=0){
                if(heli>=0&& heli<jTable1.getRowCount()){
                    jTable1.removeRowSelectionInterval(heli, heli);
                }
                heli=row;
                jTable1.setRowSelectionInterval(heli, heli);
            }
        }
        
        
        
        });
    }
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
                
              
            }
        });
        
        
         
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
class ReadButtonTableCellRenderer extends JButton implements TableCellRenderer {
    public ReadButtonTableCellRenderer()
    {
        setOpaque(true);
    }
    @Override
    public Component getTableCellRendererComponent(JTable jtable, Object o, boolean bln, boolean bln1, int i, int i1) {
       setText((o==null)?"Read":"Read");
       return this;
    }

  
   
}